#!/usr/bin/php
<?php
/**
 * This script is a sendmail wrapper for php to log calls of the php mail() function.
 */
$stdin = fopen('php://stdin', 'r');
$stderr = fopen('php://stderr', 'w');

while ($line = fgets($stdin)) {
  fwrite($stderr, $line);
}

fflush($stderr);
fclose($stderr);
